advisor:
  bucket: "project-mlops-bucket"
  raw_key: "raw-data/advisor_dataset.csv"
  processed_prefix: "processed-data/advisor/"
  train_key: "processed-data/advisor/train.jsonl"
  test_key: "processed-data/advisor/test.jsonl"

  mlflow_tracking_uri: "http://13.48.49.105:5000"
  mlflow_experiment: "advisor_experiment"
  mlflow_model_name: "advisor_model"

  # base_model: "UBC-NLP/AraT5v2-base-1024"   
  base_model: "google-t5/t5-small"
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.1
  lr: 2e-4
  epochs: 3
  batch_size: 4
  max_new_tokens: 50
